CREATE TABLE topicos(
    id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    titulo VARCHAR(100) UNIQUE NOT NULL,
    mensaje VARCHAR(255) UNIQUE NOT NULL,
    fecha_creacion DATETIME DEFAULT CURRENT_TIMESTAMP,
    fecha_modificacion DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);